server.port: 8090

grafikowy:
  security:
    secret: LubieKotletySchabowe
    expirationTime: 864000000
    tokenPrefix: 'Bearer '
    headerName: Authorization

spring:
  datasource:
      username: sa
      password:
  h2:
    console:
      enabled: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE